### ISSUE TITLE
Tutorial pages are missing instructions/codeblocks

### ISSUE THREAD

**Issue by devminded** [aptly-dev/www.aptly.info#82]
There are no code presented in the tutorials. Only the text around which makes for strange reading.

The view source is saying "raw HTML omitted" instead of showing the codeblocks. My guess is that the Markdown generator is misconfigured.

![huh](https://user-images.githubusercontent.com/10235454/77070588-c8c77500-69ea-11ea-8532-d44b50df3190.PNG)

**Comment by abeluck** [comment]
Came here to report the same.

**Comment by abeluck** [comment]
Not sure this project is very active anymore.. we moved forward with a different tool.

**Comment by VChernenkoRT** [comment]
same here

  | 
  |

**Comment by Smarre** [comment]
> Not sure this project is very active anymore.. we moved forward with a different tool.

@abeluck to what tool you moved to?

**Comment by abeluck** [comment]
@Smarre reprepro https://wiki.debian.org/DebianRepository/SetupWithReprepro

**Comment by Smarre** [comment]
@abeluck Okay, I started to investigate aptly since reprepro was not really good for my use case...
